/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gpacalculator1;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author 2002a
 */
public class frame2 extends javax.swing.JFrame {
    
    /**
     * Creates new form frame2
     */
    private ArrayList<JButton> semesterButtons;
    private ArrayList<Semester> semesters;
    String ProgramFrame2;
    String nameFrame2;
    int levelFrame2;
    
    public frame2() {
        initComponents();
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        coursesPanel.setViewportView(panel);
        semesters = new ArrayList<>();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        coursesPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FCI - SCU GPA Calculator");
        setMaximumSize(new java.awt.Dimension(693, 477));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/166.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/166_6_.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("");
        jLabel2.setMaximumSize(new java.awt.Dimension(317, 286));
        jLabel2.setMinimumSize(new java.awt.Dimension(317, 286));
        jLabel2.setPreferredSize(new java.awt.Dimension(317, 286));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("General");

        jButton1.setBackground(new java.awt.Color(124, 235, 235));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Go");
        jButton1.setMargin(new java.awt.Insets(5, 14, 5, 14));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Number Of Semesters :");

        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        coursesPanel.setBackground(new java.awt.Color(255, 255, 255));
        coursesPanel.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(coursesPanel)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(coursesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            // Clear the semesters ArrayList
        semesters.clear();

        String s = jTextField1.getText();
        if(!s.matches("\\d{1,2}")) JOptionPane.showMessageDialog(jPanel1, "Please Enter A Valid Semesters Number");
        else{
            if(Integer.parseInt(s)>16) JOptionPane.showMessageDialog(jPanel1, "Please Enter A Valid Semesters Number");
            else{
                updateCoursesPanel(Integer.parseInt(s));
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void updateCoursesPanel(int totalSemesters) {
        JPanel panel = (JPanel) coursesPanel.getViewport().getView();
        panel.removeAll();
        
        for (int i = 0; i < totalSemesters; i++) {
            Semester semester = new Semester();
            semesters.add(semester);
            
            JPanel semesterPanel = new JPanel();
            semesterPanel.add(new JLabel("Semester " + (i + 1) + ":"));
            String titleDia = "Semester " + (i + 1);

            semesterPanel.add(new JLabel("Number Of Courses:"));
            JComboBox<Integer> coursesComboBox = new JComboBox<>();
            coursesComboBox.addItem(null);
            for (int j = 1; j <= 10; j++) {
                coursesComboBox.addItem(j);
            }
            coursesComboBox.setSelectedItem(null);
            coursesComboBox.addActionListener((ActionEvent e) -> {
                // Create a dialog
                JDialog dialog = new JDialog();
                dialog.setTitle(titleDia);
                dialog.setLayout(new BoxLayout(dialog.getContentPane(), BoxLayout.Y_AXIS));
               
                // Get the number of courses from the combo box
                Integer totalCourses = (Integer) coursesComboBox.getSelectedItem();
                if (totalCourses == null) {
                    return;
                }

                ArrayList<JComboBox<Integer>> creditHoursComboBoxes = new ArrayList<>();
                ArrayList<JTextField> gradeFields = new ArrayList<>();

                // Add course details to the dialog
                for (int j = 0; j < totalCourses; j++) {
                    JPanel coursePanel = new JPanel();
                    coursePanel.add(new JLabel("Course " + (j + 1) + ":"));

                    coursePanel.add(new JLabel("Credits:"));
                    JComboBox<Integer> creditHoursComboBox = new JComboBox<>();
                    for (int k = 1; k <= 8; k++) {
                        creditHoursComboBox.addItem(k);
                    }
                    creditHoursComboBox.setSelectedIndex(2);
                    coursePanel.add(creditHoursComboBox);
                    creditHoursComboBoxes.add(creditHoursComboBox);

                    coursePanel.add(new JLabel("grade:"));
                    JTextField gradeField = new JTextField(4);
                    coursePanel.add(gradeField);
                    gradeFields.add(gradeField);

                    dialog.add(coursePanel);
                }

                JButton saveButton = new JButton("Save");
                saveButton.addActionListener((ActionEvent event) -> {
                    semester.courses.clear();
                    for (int j = 0; j < totalCourses; j++) {
                        String gradeText = gradeFields.get(j).getText();
                        if (gradeText.isEmpty()) {
                            JOptionPane.showMessageDialog(dialog, "Please Enter A Grade");
                            return;
                        }
                        double grade = Double.parseDouble(gradeText);
                        if (grade < 0.0 || grade > 100.0) {
                            JOptionPane.showMessageDialog(dialog, "Please Enter A Valid Courses Grade between 0.00 to 100.00");
                            return;
                        }
                        Integer credits = (Integer) creditHoursComboBoxes.get(j).getSelectedItem();
                        if (credits == null) {
                            JOptionPane.showMessageDialog(dialog, "Please Select Credits");
                            return;
                        }
                    }
                    for (int j = 0; j < totalCourses; j++) {
                        int credits = (int) creditHoursComboBoxes.get(j).getSelectedItem();
                        double grade = Double.parseDouble(gradeFields.get(j).getText());
                        Course course = new Course(credits, grade);
                        semester.addCourse(course);
                    }
                    dialog.dispose();
                });
                dialog.add(saveButton);

                // Show the dialog
                dialog.pack();
                dialog.setLocationRelativeTo(coursesComboBox);
                dialog.setVisible(true);
            });

            semesterPanel.add(coursesComboBox);
            panel.add(semesterPanel);
        }
        JPanel calculatePanel = new JPanel();
        calculatePanel.setLayout(new BoxLayout(calculatePanel, BoxLayout.X_AXIS));
        calculatePanel.add(Box.createHorizontalGlue());
        JButton calculateButton = new JButton("Calculate");
        calculatePanel.add(calculateButton);
        calculateButton.setBackground(new java.awt.Color(124, 235, 235));
        calculateButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.setMargin(new java.awt.Insets(5, 14, 5, 14));
        // Assuming you have a JButton calculateButton
        calculateButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                double allSemestersGPA = calculateAllSemestersGPA();
                if (Double.isNaN(allSemestersGPA)) {
                    JOptionPane.showMessageDialog(frame2.this, "Please Enter Courses's Grades");
                    return;
                }
                JDialog dialog = new JDialog();
                dialog.setTitle(nameFrame2 + "'s Cumulative GPA");
                dialog.setLayout(new BoxLayout(dialog.getContentPane(), BoxLayout.Y_AXIS));
                dialog.setPreferredSize(new Dimension(600, 500)); // Set preferred size

                dialog.add(createLabelPanel("Name:", nameFrame2));
                dialog.add(createLabelPanel("Program:", ProgramFrame2));
                dialog.add(createLabelPanel("Level:", String.valueOf(levelFrame2)));

                for (int i = 0; i < semesters.size(); i++) {
                    dialog.add(createLabelPanel("Semester " + (i + 1) + " GPA:", String.format("%.2f", semesters.get(i).getCumulativeGPA())));
                }

                
                dialog.add(createLabelPanel("Cumulative GPA:", String.format("%.2f", allSemestersGPA)));

                String gradeLetter;
                if (allSemestersGPA < 1.0) gradeLetter = "F";
                else if (allSemestersGPA < 1.6) gradeLetter = "D";
                else if (allSemestersGPA < 1.9) gradeLetter = "D+";
                else if (allSemestersGPA < 2.2) gradeLetter = "C";
                else if (allSemestersGPA < 2.5) gradeLetter = "C+";
                else if (allSemestersGPA < 2.8) gradeLetter = "B";
                else if (allSemestersGPA < 3.1) gradeLetter = "B+";
                else if (allSemestersGPA < 3.4) gradeLetter = "A-";
                else if (allSemestersGPA < 3.7) gradeLetter = "A";
                else gradeLetter = "A+";

                dialog.add(createLabelPanel("Grade:", gradeLetter));

                dialog.pack();
                dialog.setVisible(true);
            }

            private JPanel createLabelPanel(String labelText, String valueText) {
                JPanel panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
                JLabel label = new JLabel("<html><b>" + labelText + "</b></html>");
                label.setPreferredSize(new Dimension(200, 25)); // Set preferred size
                panel.add(label);
                panel.add(new JLabel(valueText));
                return panel;
            }
        });
        panel.add(calculateButton);
        
        panel.revalidate();
        panel.repaint();
    }
    public class Course {
        private int credits;
        private double grade;

        public Course(int credits, double grade) {
            this.credits = credits;
            this.grade = grade;
        }

        public int getCredits() {
            return credits;
        }

        public double getGrade() {
            return grade;
        }
        
        public double getWeightedGPA() {
            return ((0.06 * grade) - 2.00) * credits;
        }
    }
    public class Semester {
        private ArrayList<Course> courses;

        public Semester() {
            courses = new ArrayList<>();
        }

        public void addCourse(Course course) {
            courses.add(course);
        }

        public ArrayList<Course> getCourses() {
            return courses;
        }
        
        public double getCumulativeGPA() {
            double totalWeightedGPA = 0.0;
            int totalCredits = 0;
            for (Course course : courses) {
                totalWeightedGPA += course.getWeightedGPA();
                totalCredits += course.getCredits();
            }
            return totalWeightedGPA / totalCredits;
        }

        public int getTotalCredits() {
            int totalCredits = 0;
            for (Course course : courses) {
                totalCredits += course.getCredits();
            }
            return totalCredits;
        }
    }
    private double calculateAllSemestersGPA() {
        double totalWeightedGPA = 0.0;
        int totalCredits = 0;
        for (Semester semester : semesters) {
            totalWeightedGPA += semester.getCumulativeGPA() * semester.getTotalCredits();
            totalCredits += semester.getTotalCredits();
        }
        return totalWeightedGPA / totalCredits;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane coursesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
